<a href="https://colab.research.google.com/github/khemsu/tensorflow/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
# x=np.array([1,2,3,4,5], dtype='int32')
x =np.array([[1,2,3],[4,5,6]]) #2D
print(x)
x.shape #shape
# x.ndim #dimension



[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
#Get a specific element [r,c] starting from index0
x[0,2]

3

In [ ]:
a=np.array([[[1,2],[3,4]],[[5,6],[6,7]]])
print(a)
a.shape
# a.ndim

[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]


(2, 2, 2)

In [ ]:
#getting specific rows
a[1,1,:] #[matrix,row,col]

array([6, 7])

Initiating Different Types of Arrays

In [ ]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#all 1s matrix
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.13967512, 0.4736337 ],
       [0.58616654, 0.06331159],
       [0.06678139, 0.10756992],
       [0.06085078, 0.63014853]])

In [ ]:
#random integer values
np.random.randint(4,8, size=(3,3)) #(startindex,endindex, size)


array([[7, 5, 7],
       [5, 7, 6],
       [5, 6, 6]])

In [ ]:
#repaeating array
arr= np.array([[1,2,3]])
arr.shape
# arr.ndim
r1 = np.repeat(arr,2, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]]


Becareful while copying

In [ ]:
a=np.array([1,2,3])
b=a.copy()
b[0]= 100 #use copy function
print(b)
print(a)

[100   2   3]
[1 2 3]


Statistic

In [ ]:
stats = np.array([[1,2,3],[6,7,8]])
np.min(stats, axis=0)

array([1, 2, 3])

In [ ]:
np.max(stats)

8

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
