<a href="https://colab.research.google.com/github/khemsu/tensorflow/blob/main/tensorbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf


Initialization of tensor

In [12]:
# x=tf.constant(4)
# print(x)

x= tf.constant(5, shape=(2,1), dtype=tf.float32)
print(x)

#creating 2,3 shape
y= tf.constant([[1,2,3],[4,5,6]])
print(y)

x=tf.ones(shape=(3,3))
print(x)

x=tf.zeros(shape=(2,3))
print(x)


tf.Tensor(
[[5.]
 [5.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


Mathematical operation


In [14]:
x= tf.constant([1,2,3])
y=tf.constant([9,8,7])

z=tf.add(x,y)
print(z)

#z=tf.subtract(x,y) for element wise addition
#z=tf.multiply(x,y) for element wise multiplication

z=tf.tensordot(x,y, axes=1) #for element wise multiplication and summing up
print(z)







tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)


Indexing

In [30]:
x = tf.constant([0,1,1,2,3,1,2,3,])
print(x[:]) #prints all element
print(x[1:]) #print every element except the first element
print(x[1:3]) #prints between 1 to 3 starting from index 0

print(x[:-1]) #prints all except last element


#for matrix

x= tf.constant([[1,2],
                 [3,4],
                  [5,6]])
print(x[0,:]) #only the first part
print(x[0:2,:]) #for Two rows





tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 1 2 3 1 2], shape=(7,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


Reshaping

In [32]:
x= tf.range(9)
print(x)

x=tf.reshape(x, (3,3))
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
